### ISSUE TITLE
module 'cupy.cuda' has no attribute 'compile_with_cache'

### ISSUE THREAD

**Issue by O-O1024** [leoShen917/DreamMover#2]
After training lora, and click run, an error occurs:
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/root/DreamMover/gradio_ui.py", line 178, in run_mover
    gen_image = main(args)
  File "/root/DreamMover/main.py", line 47, in main
    flow1to2,flow2to1=predict_z0(model,args,sup_res_h,sup_res_w)
  File "/root/DreamMover/utils/predict.py", line 92, in predict_z0
    out_soft12 = splat_flow(input_code[:1], input_code[1:], flow1to2, time)
  File "/root/DreamMover/utils/predict.py", line 45, in splat_flow
    out_soft = softsplat(tenIn=frame1, tenFlow=flow*time, tenMetric=(-10.0 * tenMetric).clip(-10.0, 10.0), strMode='soft')
  File "/root/DreamMover/third_party/softsplat.py", line 256, in softsplat
    tenOut, Sq = softsplat_func.apply(tenIn, tenFlow, True)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 123, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/root/DreamMover/third_party/softsplat.py", line 296, in forward
    cuda_launch(cuda_kernel('softsplat_out', '''
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "/root/DreamMover/third_party/softsplat.py", line 225, in cuda_launch
    return cupy.cuda.compile_with_cache(objCudacache[strKey]['strKernel'], tuple(['-I ' + os.environ['CUDA_HOME'], '-I ' + os.environ['CUDA_HOME'] + '/include'])).get_function(objCudacache[strKey]['strFunction'])
  File "/root/miniconda3/lib/python3.10/site-packages/cupy/cuda/__init__.py", line 84, in __getattr__
    raise AttributeError(
AttributeError: module 'cupy.cuda' has no attribute 'compile_with_cache'
```

**Comment by leoShen917** [comment]
My CUDA version is 11.7 and I am using cupy11x. Please check if your CUDA version conflicts with cupy11x.
